### ISSUE TITLE
MsOfficeTracker: Exception when restarting the computer

### ISSUE THREAD

**Issue by manulita** [sealuzh/PersonalAnalytics#151]
Two of the participants of the study experienced this crash which sometimes happens when the computer is restarted, while the application is running. I am not sure if both had the same exception.

Report from participant A:
If you try to restart the computer while the app is running, it crashes.

1) Here is Windows Event log info:
Application: PersonalAnalytics.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
   at System.Windows.Application..ctor()
   at PersonalAnalytics.App.Main()

2) Here is errors.log:
Log Entry: 2:01:55 AM Wednesday, March 8, 2017
An error occurred while processing this request. :    at Microsoft.OData.Client.QueryResult.EndExecuteQuery[TElement](Object source, String method, IAsyncResult asyncResult)
   at Microsoft.OData.Client.DataServiceRequest.EndExecute[TElement](Object source, DataServiceContext context, String method, IAsyncResult asyncResult)
   at Microsoft.OData.Client.DataServiceQuery`1.EndExecute(IAsyncResult asyncResult)
   at Microsoft.OData.ProxyExtensions.DataServiceContextWrapper.<>c__DisplayClass38`2.<ExecuteAsync>b__36(IAsyncResult r)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.OData.ProxyExtensions.DataServiceContextWrapper.<ExecuteAsync>d__3a`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MsOfficeTracker.Helpers.Office365Api.<GetNumberOfUnreadEmailsInInbox>d__19.MoveNext()
-------------------------------

Screenshot from Participant B:
![image](https://cloud.githubusercontent.com/assets/11174188/23979312/f8dc69fa-09b5-11e7-8a6c-5a2f2cb4aaa9.png)

**Comment by casaout** [comment]
thanks! I've also experienced this error a few times in the past. The problem is that the stacktrace only points us to 'MsOfficeTracker.Helpers.Office365Api.d__19.MoveNext()' and this only lets me know the issue is in the MsOfficeTracker, but it's unclear where exactly...

**Comment by casaout** [comment]
Closed because not more/enough info to reproduce...
