### ISSUE TITLE
Bug: After successful update, PA doesn't start anymore

### ISSUE THREAD

**Issue by casaout** [sealuzh/PersonalAnalytics#168]
Recently we've experienced an issue when updating the PA-application (via Jenkins): After a successful update, the application doesn't restart (and only restarts the next time the user restarts the computer).

Any ideas/suggestions are welcome. We don't know much about this issue yet...

**Comment by s-mueller** [comment]
I found this issue: https://github.com/sealuzh/PersonalAnalytics/issues/115

It seems that we were unsure whether the restart works on Windows 7. However, the restart issue is not limited to Windows 7 machines, right?

Do we know which branch/build it affects? Then we could start looking into the build processes and check whether there are any differences between successful versions and the ones leading to this problem.

**Comment by casaout** [comment]
I've experienced the issue on two Win10 machines on the master branch (possibly also a biometrics branch or the study branch)

**Comment by s-mueller** [comment]
I just made a couple of updates on my machine with the dev and biometrics branch but never had any problem. At least this bug seems to occur not every time an update is done.

**Comment by s-mueller** [comment]
And here is another similar bug. Could it be that the problem is related to different publisher names?

https://github.com/sealuzh/PersonalAnalytics/issues/114

**Comment by casaout** [comment]
>  And here is another similar bug. Could it be that the problem is related to different publisher names?

Maybe. When did they change the last time? I should get the update within the next 6 hours - we'll see then...

**Comment by s-mueller** [comment]
Here is the error log from the crash I had when shutting down PA:

```
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2017-04-18T16:50:22.456719700Z" /> 
  <EventRecordID>6547</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>SEBASTIANMLB5A1</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>PersonalAnalytics.exe</Data> 
  <Data>1.0.0.0</Data> 
  <Data>58f640a8</Data> 
  <Data>unknown</Data> 
  <Data>0.0.0.0</Data> 
  <Data>00000000</Data> 
  <Data>c0000005</Data> 
  <Data>07308af0</Data> 
  <Data>1cf8</Data> 
  <Data>01d2b8638ff5d640</Data> 
  <Data>C:\Users\sebastianmuller\AppData\Local\Apps\2.0\50DOL4DV.7TG\QV0E5EGE.53G\pers..tion_a7e79151be2a7d70_0000.0009_d6a92279bd921da9\PersonalAnalytics.exe</Data> 
  <Data>unknown</Data> 
  <Data>6e7cfdca-3eab-43b2-b267-0dece6cfe748</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>
```

And at the same time I also have a StackTrace:

```
Log Name:      Application
Source:        .NET Runtime
Date:          18.04.17 18:50:22
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      SEBASTIANMLB5A1
Description:
Application: PersonalAnalytics.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Retrospection.HttpServer.Stop()
   at Retrospection.Handler.Stop()
   at PersonalAnalytics.TrackerManager.Stop(Boolean)
   at PersonalAnalytics.TrackerManager.<SetContextMenuOptions>b__33_6(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at PersonalAnalytics.App.Main()


Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2017-04-18T16:50:22.269220700Z" />
    <EventRecordID>6546</EventRecordID>
    <Channel>Application</Channel>
    <Computer>SEBASTIANMLB5A1</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: PersonalAnalytics.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Retrospection.HttpServer.Stop()
   at Retrospection.Handler.Stop()
   at PersonalAnalytics.TrackerManager.Stop(Boolean)
   at PersonalAnalytics.TrackerManager.&lt;SetContextMenuOptions&gt;b__33_6(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at PersonalAnalytics.App.Main()

</Data>
  </EventData>
</Event>
```

**Comment by casaout** [comment]
New Stacktrace:

`Anwendung: PersonalAnalytics.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: System.Runtime.Remoting.RemotingException

Server stack trace: 
   bei System.Runtime.Remoting.Channels.Ipc.IpcPort.Read(Byte[] data, Int32 offset, Int32 length)
   bei System.Runtime.Remoting.Channels.Ipc.PipeStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   bei System.Runtime.Remoting.Channels.SocketHandler.ReadFromSocket(Byte[] buffer, Int32 offset, Int32 count)
   bei System.Runtime.Remoting.Channels.SocketHandler.Read(Byte[] buffer, Int32 offset, Int32 count)
   bei System.Runtime.Remoting.Channels.SocketHandler.ReadAndMatchFourBytes(Byte[] buffer)
   bei System.Runtime.Remoting.Channels.Tcp.TcpSocketHandler.ReadAndMatchPreamble()
   bei System.Runtime.Remoting.Channels.Tcp.TcpSocketHandler.ReadVersionAndOperation(UInt16& operation)
   bei System.Runtime.Remoting.Channels.Ipc.IpcClientHandler.ReadHeaders()
   bei System.Runtime.Remoting.Channels.Ipc.IpcClientTransportSink.ProcessMessage(IMessage msg, ITransportHeaders requestHeaders, Stream requestStream, ITransportHeaders& responseHeaders, Stream& responseStream)
   bei System.Runtime.Remoting.Channels.BinaryClientFormatterSink.SyncProcessMessage(IMessage msg)
   bei System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(System.Runtime.Remoting.Messaging.IMessage, System.Runtime.Remoting.Messaging.IMessage)
   bei System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(System.Runtime.Remoting.Proxies.MessageData ByRef, Int32)
   bei PersonalAnalytics.Helpers.SingleInstance`1+IPCRemoteService[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InvokeFirstInstance(System.Collections.Generic.IList`1<System.String>)
   bei PersonalAnalytics.Helpers.SingleInstance`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SignalFirstInstance(System.String, System.Collections.Generic.IList`1<System.String>)
   bei PersonalAnalytics.Helpers.SingleInstance`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InitializeAsFirstInstance(System.String)
   bei PersonalAnalytics.App.Main()

`

**Comment by s-mueller** [comment]
Tried to fix this issue in this commit: https://github.com/sealuzh/PersonalAnalytics/commit/aafe454ee474292da920ad0a1493d36b9dc15d60

The idea is based on: https://searchcode.com/codesearch/view/28793422/

**Comment by s-mueller** [comment]
This commit also belongs to this issue: https://github.com/sealuzh/PersonalAnalytics/commit/bb43f02838a36ff466531fee04bbc5753c8890aa

**Comment by s-mueller** [comment]
https://github.com/sealuzh/PersonalAnalytics/commit/863bd669656299c0cf4c73b79aadd00fc91b7f90

**Comment by casaout** [comment]
undid recent changes & made change back to check for updates every 6hrs (and 5mins on dev): https://github.com/sealuzh/PersonalAnalytics/commit/3dc23e8ad04e8f12b93058b81aa1009de0f07190

Thanks @s-mueller!
