### ISSUE TITLE
Bug on a study participant's machine

### ISSUE THREAD

**Issue by casaout** [sealuzh/PersonalAnalytics#20]
participant: F40

Log Entry: 2:58:12 PM Thursday, January 28, 2016
Mailbox info is stale. :    at Microsoft.OData.ProxyExtensions.DataServiceContextWrapper.<ExecuteAsync>d__3a`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MsOfficeTracker.Helpers.Office365Api.<GetNumberOfEmailsInInbox>d__21.MoveNext()

Log Entry: 4:51:47 PM Monday, February 8, 2016
The SMTP address has no mailbox associated with it. :    at Microsoft.OData.ProxyExtensions.DataServiceContextWrapper.<ExecuteAsync>d__3a`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MsOfficeTracker.Helpers.Office365Api.<GetNumberOfEmailsSent>d__21.MoveNext()

**Comment by casaout** [comment]
Not enough information about the issue and only reported once.
