### ISSUE TITLE
MsOfficeTracker: Bug with silent authentication

### ISSUE THREAD

**Issue by casaout** [sealuzh/PersonalAnalytics#55]
when user is logged in and wants to authenticate again... What is this about? (maybe API issue) - Does deleting the cached token-file help? (TBD)

Log Entry: 2:02:23 AM Friday, April 15, 2016
Object reference not set to an instance of an object. :    at MsOfficeTracker.Helpers.Office365Api.<SignIn>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MsOfficeTracker.Helpers.Office365Api.<TrySilentAuthentication>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MsOfficeTracker.Helpers.Office365Api.<Authenticate>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MsOfficeTracker.Daemon.<Start>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by casaout** [comment]
as a result of the API change, it is currently not possible anymore to easily get the user authenticated Name and Email. I will have to look for another way to do this later.
