### ISSUE TITLE
Bug: Manually open pop-up, interval pop-up opens (because of the timer) results in Exception

### ISSUE THREAD

**Issue by casaout** [sealuzh/PersonalAnalytics#57]
Then I went for a meeting. When I got back I had two session pop-ups open. (I think I might have opened one manually before I left and kept open).

I responded to the top survey first, then to the second survey. For the second survey I got an error:

Object reference not set to an instance of an object. :    at UserEfficiencyTracker.Daemon.SaveIntervalSurvey(IntervalProductivityPopUp popup) in D:\Development\Repos\PersonalAnalytics\src\client\AM.PA.MonitoringTool\UserEfficiencyTracker\Daemon.cs:line 289
   at UserEfficiencyTracker.Daemon.HandleIntervalPopUpResponse(IntervalProductivityPopUp popup) in D:\Development\Repos\PersonalAnalytics\src\client\AM.PA.MonitoringTool\UserEfficiencyTracker\Daemon.cs:line 263
   at UserEfficiencyTracker.Daemon.<>c__DisplayClass21_0.<RunSurvey>b__0() in D:\Development\Repos\PersonalAnalytics\src\client\AM.PA.MonitoringTool\UserEfficiencyTracker\Daemon.cs:line 239
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Thanks @tzimmermsr for reporting.

**Comment by casaout** [comment]
Closing as reported for legacy version of PersonalAnalytics.
